### ISSUE TITLE
error with REDIS_URL

### ISSUE THREAD

**Issue by kesavkolla** [chatwoot/charts#89]
when I deploy the chart I am getting failures like:

```
+ exec bundle exec rails s -p 3000 -b 0.0.0.0
=> Booting Puma
=> Rails 6.1.6.1 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
/usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "redis://:$(REDIS_PASSWORD)@cache.chat.svc.cluster.local:<no value>" (URI::InvalidURIError)
	from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
	from /usr/local/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
	from /gems/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/redis_connection.rb:102:in `log_info'
	from /gems/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/redis_connection.rb:32:in `create'
	from /gems/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:136:in `redis='
	from /app/config/initializers/sidekiq.rb:6:in `block in <main>'
	from /gems/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:83:in `configure_client'
	from /app/config/initializers/sidekiq.rb:5:in `<main>'
	from /gems/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	from /gems/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	from /gems/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:326:in `block in load'
	from /gems/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /gems/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:326:in `load'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /gems/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:680:in `load_config_initializer'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `each'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:50:in `each'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'
	from /app/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	from /gems/ruby/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:39:in `start'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
	from /gems/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
	from /gems/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /gems/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by vishnu-narayanan** [comment]
It appears to be an issue with your REDIS URL config. Could you share your `REDIS_URL` value?

**Comment by vishnu-narayanan** [comment]
Please reopen if issue persists.
